#!/usr/bin/env bash
# Security gate for a built APK. Usage: mobile/e2e/check-apk.sh [apk] [--release]
# Fails (exit 1) if the app asks for any permission, allows backups or cleartext traffic, exports unexpected
# components, or (with --release) is debuggable.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../env.sh
source "$HERE/../env.sh"
APK="${1:-$HERE/../android/app/build/outputs/apk/debug/app-debug.apk}"
RELEASE=0; [[ "${2:-}" == "--release" ]] && RELEASE=1
AAPT="$ANDROID_HOME/build-tools/36.0.0/aapt2"
# exported components we accept: our launcher, and AndroidX's profile installer (guarded by android.permission.DUMP)
ALLOWED_EXPORTED=(".MainActivity" "com.mcampana.pokeradvisor.MainActivity" "androidx.profileinstaller.ProfileInstallReceiver")

fail=0
check() { if [[ "$2" == ok ]]; then echo "ok   $1"; else echo "FAIL $1"; fail=1; fi; }

# the dynamic-receiver permission is generated by AndroidX for the app itself and is not grantable to others
perms="$("$AAPT" dump permissions "$APK" | grep '^uses-permission' | grep -v 'DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION' || true)"
if [[ -z "$perms" ]]; then check "no permissions requested (offline app)" ok; else check "unexpected permissions: ${perms//$'\n'/; }" fail; fi

manifest="$("$AAPT" dump xmltree --file AndroidManifest.xml "$APK")"
if grep -q 'allowBackup.*=false' <<<"$manifest"; then check "backups disabled" ok; else check "allowBackup is not false" fail; fi
if grep -q 'usesCleartextTraffic.*=false' <<<"$manifest"; then check "cleartext traffic disabled" ok; else check "usesCleartextTraffic is not false" fail; fi

exported="$(awk '/E: (activity|receiver|service|provider)/{el=1} el && /android:name\(/{match($0,/"[^"]+"/); n=substr($0,RSTART+1,RLENGTH-2)}
                 el && /android:exported\(.*\)=true/{print n}' <<<"$manifest")"
bad=""
while IFS= read -r name; do
  [[ -z "$name" ]] && continue
  ok=0; for a in "${ALLOWED_EXPORTED[@]}"; do [[ "$name" == "$a" ]] && ok=1; done
  [[ $ok == 1 ]] || bad+="$name "
done <<<"$exported"
if [[ -z "$bad" ]]; then check "only expected components are exported" ok; else check "unexpected exported components: $bad" fail; fi

if grep -q 'debuggable.*=true' <<<"$manifest"; then
  if [[ $RELEASE == 1 ]]; then check "release build is not debuggable" fail; else echo "info debuggable build (fine for debug, not for release)"; fi
else
  check "not debuggable" ok
fi
# WebView remote debugging exposes the app's data to anyone with a USB cable. Capacitor's default is not
# "off" (a non-debuggable release still opened the socket), so a release must say `false` explicitly.
cfg="$(unzip -p "$APK" assets/capacitor.config.json 2>/dev/null || true)"
if grep -Eq '"webContentsDebuggingEnabled": *false' <<<"$cfg"; then
  check "WebView remote debugging is explicitly off" ok
elif [[ $RELEASE == 1 ]]; then
  check "WebView remote debugging must be explicitly off in a release" fail
else
  echo "info WebView remote debugging is not explicitly off (fine for a test build)"
fi
exit $fail
